import assert from 'node:assert/strict';
import test from 'node:test';
import { LocalFirstRoutePolicy, RoutePolicyError } from '../dist/index.js';

const candidate = (id, extra = {}) => ({ id, discoverySource: id.includes('lan') ? 'mdns' : 'iroh', bootstrapEvidence: id.includes('lan') ? 'mdns' : 'presence', transportAdapter: 'fake', addressHints: ['redacted'], trustBinding: { peerId: 'peer', verified: true }, kind: id.includes('relay') ? 'relay' : 'direct', locality: id.includes('lan') ? 'local' : 'remote', cost: id.includes('relay') ? 10 : 0, latencyMs: id.includes('relay') ? 100 : 5, available: true, reachable: true, ...extra });
const adapterFor = (outcomes) => ({ connect: async (c, { signal }) => { const outcome = outcomes[c.id]; if (outcome) await outcome(signal); if (signal.aborted) throw new Error('aborted'); return { id: `session-${c.id}`, candidateId: c.id, close: async () => {} }; } });
const clock = () => { let now = 1_700_000_000_000; return { clock: { now: () => now }, advance: (ms) => { now += ms; } }; };

test('ranks verified reachable local direct routes before relay', () => { const policy = new LocalFirstRoutePolicy(); const ranked = policy.rank([candidate('relay'), candidate('lan')]); assert.deepEqual(ranked.map((x) => x.id), ['lan', 'relay']); });
test('direct timeout falls through to relay and reports route', async () => { const diagnostics = []; const policy = new LocalFirstRoutePolicy({ diagnostics: (e) => diagnostics.push(e) }); const decision = await policy.connect([candidate('lan'), candidate('relay')], adapterFor({ lan: async () => { throw new RoutePolicyError('timeout'); } }), { peerId: 'peer', trust: async () => true, maxRace: 1 }); assert.equal(decision.routeId, 'relay'); assert.ok(diagnostics.some((e) => e.name === 'route_selected')); });
test('trust mismatch is terminal and cannot downgrade', async () => { const policy = new LocalFirstRoutePolicy(); await assert.rejects(() => policy.connect([candidate('lan'), candidate('relay')], adapterFor({}), { peerId: 'peer', trust: async () => false }), (e) => e instanceof RoutePolicyError && e.failure === 'auth_failure'); });
test('racing cancels loser', async () => { let cancelled = false; const policy = new LocalFirstRoutePolicy(); const adapter = { connect: async (c, { signal }) => { if (c.id === 'slow') await new Promise((resolve) => { signal.addEventListener('abort', () => { cancelled = true; resolve(); }, { once: true }); }); return { id: c.id, candidateId: c.id, close: async () => {} }; } }; const decision = await policy.connect([candidate('slow', { locality: 'remote' }), candidate('fast', { locality: 'local' })], adapter, { peerId: 'peer', trust: async () => true, maxRace: 2 }); assert.equal(decision.routeId, 'fast'); assert.equal(cancelled, true); });
test('network transition invalidates generation', () => { const clockState = clock(); let listener; const policy = new LocalFirstRoutePolicy({ ...clockState, network: { subscribe: (fn) => { listener = fn; return () => { listener = undefined; }; } } }); listener({ kind: 'changed' }); assert.doesNotThrow(() => policy.invalidateNetwork()); policy.dispose(); });
test('backoff is deterministic with injected randomness', () => { const policy = new LocalFirstRoutePolicy({ random: () => 0 }); assert.equal(policy.backoff('x', { baseBackoffMs: 100 }), 75); });
test('manual override only selects requested route', async () => { const policy = new LocalFirstRoutePolicy(); const decision = await policy.connect([candidate('lan'), candidate('relay')], adapterFor({}), { peerId: 'peer', trust: async () => true, manualRouteId: 'relay' }); assert.equal(decision.routeId, 'relay'); });
test('all candidates fail without claiming connected', async () => { const policy = new LocalFirstRoutePolicy(); await assert.rejects(() => policy.connect([candidate('lan')], adapterFor({ lan: async () => { throw new RoutePolicyError('transport_failure'); } }), { peerId: 'peer', trust: async () => true }), /all route candidates failed/); });
